# Generated by Django 5.0.1 on 2024-01-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plat',
            name='best',
            field=models.BooleanField(default=False),
        ),
    ]
