# Generated by Django 5.0.1 on 2024-01-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_plat_best'),
    ]

    operations = [
        migrations.AddField(
            model_name='plat',
            name='slug',
            field=models.SlugField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
