# Generated by Django 5.0.1 on 2024-02-08 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='balance',
        ),
    ]
