# Generated by Django 5.0.1 on 2024-02-14 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_cart_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plat',
            name='slug',
        ),
    ]
